// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJa7PGs-Gn9c4rbSQE2CUA9PetIX3vq8I',
    appId: '1:721249806336:web:f4b5b913ab569b795f10e5',
    messagingSenderId: '721249806336',
    projectId: 'lofo-app-15efa',
    authDomain: 'lofo-app-15efa.firebaseapp.com',
    storageBucket: 'lofo-app-15efa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3rllXJva-I2pz6kBbEbSsxJo-eotJ1dI',
    appId: '1:721249806336:android:256aedf1a7cc15ad5f10e5',
    messagingSenderId: '721249806336',
    projectId: 'lofo-app-15efa',
    storageBucket: 'lofo-app-15efa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUzDKOvbFtVZyfrAvauQfncHL3I2GoLc',
    appId: '1:721249806336:ios:691cfe3f13d17c2e5f10e5',
    messagingSenderId: '721249806336',
    projectId: 'lofo-app-15efa',
    storageBucket: 'lofo-app-15efa.firebasestorage.app',
    iosBundleId: 'com.example.lofoLostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvUzDKOvbFtVZyfrAvauQfncHL3I2GoLc',
    appId: '1:721249806336:ios:691cfe3f13d17c2e5f10e5',
    messagingSenderId: '721249806336',
    projectId: 'lofo-app-15efa',
    storageBucket: 'lofo-app-15efa.firebasestorage.app',
    iosBundleId: 'com.example.lofoLostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJa7PGs-Gn9c4rbSQE2CUA9PetIX3vq8I',
    appId: '1:721249806336:web:53c78d3022cfd7d85f10e5',
    messagingSenderId: '721249806336',
    projectId: 'lofo-app-15efa',
    authDomain: 'lofo-app-15efa.firebaseapp.com',
    storageBucket: 'lofo-app-15efa.firebasestorage.app',
  );
}
